### PR TITLE
[FE-16233] Setup x and y dims for line and poly layer

### PR DESCRIPTION
**Pull request by johallar**
# Merge Checklist
## :wrench: Issue(s) fixed:
- [ ] Author referenced issue(s) fixed by this PR:
- [ ] Fixes #0

## :smoking: Smoke Test
- [ ] Works in chrome
- [ ] Works in firefox
- [ ] Works in safari
- [ ] Works in ie edge
- [ ] Works in ie 11

## :ship: Merge
- [ ] author crafted PR's title into release-worthy commit message.

### CODE REVIEW

**Review by cmatzenbach — APPROVED** [review]
LGTM

**Comment by johallar** [comment]
@vastcharade gonna merge this so we have a fix in, but any additional feedback welcome i'll open another PR if so!

**Comment by vastcharade** [comment]
shoot, sorry, I meant to look at this. Sorry, fell thru my cracks. Will approve.

**Review by vastcharade — COMMENTED** [review]
lgtm

**Pull request merged**
