### PR TITLE
[FE-17686] Human-readable missing hit test cols error string

### PR DESCRIPTION
**Pull request by cmatzenbach**
Catches missing hit test column error string returned from BE and replaces with human-readable error message.

For proof, here is me forcefully pushing an invalid column into the hit testing, showing the correct error coming back from the BE (and showing no crash):

https://github.com/heavyai/heavyai-charting/assets/15268289/9b229c9d-a6e4-41e0-8e39-a4208be70507

Here is after the FE fix to turn that into a human-readable error message:

https://github.com/heavyai/heavyai-charting/assets/15268289/25e3221c-e4b8-4699-86f6-c89ab597028b

### CODE REVIEW

**Comment by mapd-bot-os** [comment]
build failed

**Comment by mapd-bot-os** [comment]
build failed

**Review by israelvicars — APPROVED** [review]

**Comment by mapd-bot-os** [comment]
build failed

**Comment by mapd-bot-os** [comment]
build failed

**Comment by mapd-bot-os** [comment]
build failed

**Pull request merged**
