### PR TITLE
[FE-17444][Linemap][Joins] Correct table isn't used for size measure

### PR DESCRIPTION
**Pull request by cjvil**
Use the table property on the size measure to accommodate joined sources

### CODE REVIEW

**Comment by mapd-bot-os** [comment]
build succeeded

**Comment by mapd-bot-os** [comment]
build succeeded

**Review by johallar — APPROVED** [review]

**Comment by cjvil** [comment]
retest this please

**Comment by mapd-bot-os** [comment]
build succeeded

**Pull request merged**
